services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db
    volumes:
      - .:/app
    command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && gunicorn --reload --bind 0.0.0.0:8000 my_blog.wsgi:application"]

#   db:
#     image: postgres:15
#     env_file:
#       - .env
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
