# Generated by Django 5.1.2 on 2024-10-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='quicklit_uploads/'),
        ),
    ]
