# Generated by Django 5.1.2 on 2024-10-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_extended_views_blog_unique_views_blogview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='has_viewed_content',
            field=models.BooleanField(default=False),
        ),
    ]
