# Generated by Django 5.1.2 on 2024-10-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to='media/blog_images/'),
        ),
    ]
