# Generated by Django 5.1.2 on 2024-10-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brochure_file',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
