# Generated by Django 5.1.2 on 2024-10-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_brochure_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='brochure_file',
        ),
    ]
