# Generated by Django 5.1.2 on 2025-06-01 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('client_name', models.CharField(max_length=255)),
                ('client_type', models.CharField(choices=[('internal', 'Internal'), ('third_party', 'Third Party')], default='third_party', max_length=50)),
                ('application', models.CharField(blank=True, help_text='Which app/service uses this key', max_length=100)),
                ('purpose', models.TextField(blank=True, help_text='Describe purpose of key usage')),
                ('is_unlimited', models.BooleanField(default=False)),
                ('usage_limit', models.PositiveIntegerField(default=1000)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application API Key',
                'verbose_name_plural': 'Application API Keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
