# Generated by Django 5.1.2 on 2025-06-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_applicationapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationapikey',
            name='is_unlimited',
        ),
        migrations.AddField(
            model_name='applicationapikey',
            name='apply_rate_limit',
            field=models.BooleanField(default=False, help_text='Apply per-minute rate limit'),
        ),
        migrations.AddField(
            model_name='applicationapikey',
            name='enforce_quota',
            field=models.BooleanField(default=True, help_text='Enforce total usage limit'),
        ),
    ]
