# Generated by Django 5.1.2 on 2024-10-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
