# Generated by Django 5.1.2 on 2025-06-08 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_remove_applicationapikey_is_unlimited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationapikey',
            name='created_by',
        ),
        migrations.AddField(
            model_name='applicationapikey',
            name='associated_user',
            field=models.ForeignKey(default=None, help_text="Represents the user context for this API key. Requests authenticated with this key will assume this user's identity.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
