# Generated by Django 5.1.2 on 2025-06-08 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0009_alter_applicationapikey_associated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationapikey',
            name='associated_user',
            field=models.ForeignKey(help_text="Represents the user context for this API key. Requests authenticated with this key will assume this user's identity.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
